
# CONTRUIR EL JDK QUE VAMOS USAR
FROM openjdk:17-jdk-slim

# VA HACER UNA VARIABLE PARA .JAR
ARG JAR_FILE=target/to-dolist-0.0.1-SNAPSHOT.jar

# PONEMOS EL JAR / EL NOMBRE DE COMO SE VA LLAMAR
COPY ${JAR_FILE} app_todo_list.jar

# EXPONER EL PUERTO 8080 DONDE CORRERA LA APP
EXPOSE 8080

# EJECUTA EL ARCHIVO .JAR
ENTRYPOINT ["java", "-jar", "app_todo_list.jar"]